---
title: "Próbny Egzamin z Wizualizacji Danych"
output:
  word_document: default
  pdf_document: default
header-includes: \usepackage[polish]{babel}
---

Aby rozwiązanie było sprawdzane, kod musi w całości zostać poprawnie zinterpretowany. Kod powinien spełniać zasady stylu PEP8 - błędy w stylu PEP8 wpływające na interpretację kodu powodują odjęcie punktów. Każde zadanie (numerowane) powinno być w oddzielnym pliku. Po zakończonej pracy wszystkie kody umieść w jednym folderze. Spakuj folder do jednego archiwum, nazwa archiwum to numer indeksu. Plik archiwum do sprawdzenia umieść na pulpicie.

Zad.1. (10 pkt) W jenym pliku wykonaj poniższe czynności:

* stwórzy wykres funkcji $f(x) = \frac{4 - x + x^3}{6 + x - 4 x^2 + x^3}$, kolor niebieski, linia ciągła.
* liniami przerywanymi narysuj asymptoty wykresu, każda powinna być w innym kolorze (wybrane kolory muszą być inne niż niebieski)
* ustal podziałkę na obu osiach na tyle aby było widoczne wszystkie asymptoty poziome i pionowe (są trzy pionowe i jedna pozioma)
* dodaj na wykres legendę i tytuł
* zapisz wykres w formacie pdf.

Zad.2. (15 pkt) W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku `sport.xlsx` (zawarte są tam informacje popularności sportów w grupie nastolatków), upewnij się, że pierwszy wiersz nie jest ustawiony jako nagłówek.
* stwórz wykres kołowy prezentujący procentowe zainteresowanie poszczególnymi sportami. Każdy wycinek powinien być w innym kolorze i podpisany liczbą procentów (w zaokrągleniu do pełnych procentów) oraz nazwą sportu, którego dotyczy. Wykres powinien posiadać tytuł.
* na wykresie w lewym górnym rogu dodaj string ze swoim numerem indeksu.
* za pomocą kodu zapisz wykres w formacie jpg.

Inspirację do wykresu znajdziesz w pliku `zad4.png`.


Zad.3. (15 pkt) W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku `wyksz.csv` jako ramkę danych,
* w ramki danych stwórz 3 oddzielne ramki danych zawierających odpowiednie wiersze zawierające dane o wykształceniu wyższym, średnim i podstawowym,
* wzorując się na pliku `zad5.png` stwórz wykres słupkowy prezentujący dane o wykształceniu względem przedziału wiekowego. Wykres powinien posiadać odpowiedni tytuł. Legenda powinna być umieszczona po prawej stronie w połowie wysokości. Etykiety i podziałki obu osi muszą być podpisane jak w pliku `zad5.png`.


Dane pochodzą z Narodowego Spisu Ludności z roku 2002. Źródło danych: Bank danych lokalnych GUS. 